# Generated by Django 5.1 on 2024-08-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Deeler', 'Deeler')], default='Buyer', max_length=20, verbose_name='User Type'),
        ),
    ]
