# Generated by Django 5.1 on 2024-08-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='image-path'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Deeler', 'Deeler'), ('Buyer', 'Buyer')], default='Buyer', max_length=20, verbose_name='User Type'),
        ),
    ]
