# Generated by Django 5.1 on 2024-08-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_img_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer'), ('Deeler', 'Deeler')], default='Buyer', max_length=20, verbose_name='User Type'),
        ),
    ]
