# Generated by Django 5.1 on 2024-08-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Deeler', 'Deeler'), ('Seller', 'Seller'), ('Buyer', 'Buyer')], default='Buyer', max_length=20, verbose_name='User Type'),
        ),
    ]
